### ISSUE TITLE
send this link is empty

### ISSUE THREAD

**Issue by laxmanmah** [noob-hackers/seeu#3]
/ ,--. \
             | ( () ) |  ┌─┐┌─┐┌─┐ ┬ ┬
              \ `--` /   └─┐├┤ ├┤  │ │
               `-..-`    └─┘└─┘└─┘ └─┘

            ::: Tool By Noob Hackers :::
          ::: github.com/noob-hackers :::

                 CaMera HackiNg Tool

                    [1]➟ SelFie
                    [2]➟ QuIz
                    [3]➟ GuEss
                    [4]➟ SpinWheel
                    [5]➟ HopGame
                    [6]➟ BirthDay
                    [7]➟ WishBook
                    [8]➟ RPSGame
                    [9]➟ FireWorks
                    [10]➟ HappyNewYear

Select Option: 10

  [1]➟ Default    [2]➟ Custom 

SELECT OPTION: 1

[•] Starting Host Server...
[•] Starting Ngrok Server...
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[•] Link working code [000]

[-------------Google Bypass Code-------------]
<iframe name="boxwish" src="" width="100%" height="100%" frameborder="0" scrolling="yes" style="width: 100%;"> </iframe> 
[-----------Use This Code in Github----------]
[•] Send This Link: 
 
[•] Waiting for victim to open link...

**Comment by makethpanda** [comment]
Turn on your hotspot.

**Comment by iamsamir090** [comment]
Still not working...i am using this in google cloud shell

**Comment by makethpanda** [comment]
Try on termux on a mobile device.

**Comment by s77626** [comment]
Link not generating why???

**Comment by Clintonlelop** [comment]
Please why is link not generating 😥😥😥 and I've turned on  hostop

**Comment by p0dbo5** [comment]
Let see..

**Comment by AF54Rrita** [comment]
Link not generate

**Comment by Rishuu6** [comment]
How to make link ?

**Comment by Nddgold22** [comment]
Why is my link not generating I did everything

**Comment by Alexdevil14344** [comment]
Why link is not generating

**Comment by Alexdevil14344** [comment]
000

**Comment by Ahsansungur** [comment]
How to generate link ?

**Comment by hafizteamhack** [comment]
<iframe name="quiz" src="" width="100%" height="100%" frameborder="0" scrolling="yes" style="width: 100%;"> </iframe>

**Comment by LeonidDurex** [comment]
Wky link not creat ? Help please

**Comment by Sasa988** [comment]
000

**Comment by Fxkiing** [comment]
<iframe name="game" src="" width="100%" height="100%" frameborder="0" scrolling="yes" style="width: 100%;"> </iframe>

**Comment by Danish332** [comment]
<iframe name="boxwish" src="" width="100%" height="100%" frameborder="0" scrolling="yes" style="width: 100%;"> </iframe>

**Comment by dgyatoo** [comment]
<iframe name="selfie" src="" width="100%" height="100%" frameborder="0" scrolling="yes" style="width: 100%;"> </iframe>

**Comment by VRSGFX** [comment]
<iframe name="selfie" src="" width="100%" height="100%" frameborder="0" scrolling="yes" style="width: 100%;"> </iframe>
