### ISSUE TITLE
What I don't get picture of victim because I try this tool in my phone but I don't get pictures

### ISSUE THREAD

**Issue by loneumar** [noob-hackers/seeu#4]
What I don't get picture of victim because I try this tool in my phone but I don't get pictures??

**Comment by KeparYTbcc** [comment]
> did you find a solution to the problem?

nope

**Comment by Ostantont** [comment]
Так же

**Comment by HotLava30** [comment]
> did you find a solution to the problem?

You need to wait until the victim opens the camera and takes a photo, after which the image will be sent to your gallery
